### PR TITLE
Aptitude updates

### PR DESCRIPTION
**Pull request by bmwiedemann**
update our aptitude compat layer
to also be a drop-in for apt-get
and to allow the mapping of package-names

### CODE REVIEW

**Comment by KAMiKAZOW** [comment]
What would be the best approach for package name mapping under non-openSUSE distros?
One workaround would be to patch the apt-packagemap.d/* files while packaging. It's doable but also very inelegant.
I'd prefer some way to maintain the list here upstream. In 10-packagemap.pm roughly half of the remaps need to be changed for Fedora: https://github.com/openSUSE/zypper/compare/master...KAMiKAZOW:patch-1

**Comment by bmwiedemann** [comment]
Ideally, we should have a central place where we store package-name-mappings (e.g. AppStream?) and generate these files from the database.

For now, it would be nicer for you to have a 2nd block with just the differences, like this
```my %fedorapkgmap = qw(python-mysqldb MySQL-python ...);

if(os_is "fedora") {
   foreach my $k (keys(%fedorapkgmap)) { $pkgmap{$k}=$fedorapkgmap{$k} }
}```

With the os_is check still to be done.

**Comment by bmwiedemann** [comment]
@KAMiKAZOW  #65 should make this work. Can you test it?

**Comment by KAMiKAZOW** [comment]
Give me until tomorrow or the day after. I'm currently fighting allergies and it's supposed to rain to coming days.

**Pull request merged**
