### PR TITLE
Port zypper-log to python3

### PR DESCRIPTION
**Pull request by asdil12**
Bug: https://bugzilla.suse.com/show_bug.cgi?id=1156158

### CODE REVIEW

**Comment by mlandres** [comment]
Can it be done to work with 2 and 3? The script is shipped down to SLE15.

**Comment by asdil12** [comment]
Wouldn't it be easier to just not backport it?
Or is that done automatically?

**Comment by asdil12** [comment]
Bacause otherwise I would still need to rely on `xzcat` for uncompressing the logs as the `lzma` module is only added in python3.

**Comment by asdil12** [comment]
So this code would run on both python2 and 3: https://github.com/asdil12/zypper/commit/1338d8f502fcdf22ca76114ccfd139f1ff6fb5fc

BUT: On SLE15SP2 there is no python binary - only python3 for python3 as python2 is still installable.

So either we add a dependency to python in the zypper rpm, so that it pulls python2 providing the python binary, or we change the shebang to python3.

**Comment by mlandres** [comment]
> Wouldn't it be easier to just not backport it?

SLE15* is all the same sourcecode. 

> or we change the shebang to python3.

We can use `sh` to test whether /usr/bin/python or python3 is there and feed the pycode as a here-document:
```
#! /bin/sh
PYTHON=....
$PYTHON <<__EOF__
...
__EOF__
```

**Comment by asdil12** [comment]
Done.

**Comment by mlandres** [comment]
Blame python ;)
Danke!

**Comment by Conan-Kudo** [comment]
Why didn't you just do a sed in the spec file to change the shebang? That's what I do in Fedora downstream: https://src.fedoraproject.org/rpms/zypper/blob/42c0dd08551fbdd30aa0429c503c48d8eb07a356/f/zypper.spec#_106-107

**Comment by Conan-Kudo** [comment]
I've proposed a far less insane solution: https://github.com/openSUSE/zypper/pull/306

**Comment by mlandres** [comment]
The script needs to run with py2 and 3.

**Comment by Conan-Kudo** [comment]
@mlandres Not on SLE 15. Python 3 has been available forever, so there it can always run on Python 3.

**Comment by DimStar77** [comment]
This is indeed quite 'dirty' - you could just enforce python3 even down to SLE12, wherepython3 has been available.

The current shebang again avoids rpm from adding proper dependencies on an actual python interpreter - it's still relying on python 'just being there'

The approach of 'just going py3', which is supportable down to SLE12GA, would avoid that. Yu could add /usr/bin/oython3 as shebang and rpm would add this binary as a dependency - allowing to have an actually working package in all situations

**Comment by Conan-Kudo** [comment]
@DimStar77 I've proposed as such in #306.

**Comment by fcrozat** [comment]
> @DimStar77 I've proposed as such in #306.

I would suggest to alter it to use py2 on SLE12 codebase (py3 is not by default there) and py3 everywhere else.

Doing this runtime check is way too complex for no gain at all.

**Comment by mlandres** [comment]
Too much ado. Will be replaced by a bash script. getopt and sed are sufficient.

**Comment by Conan-Kudo** [comment]
> > @DimStar77 I've proposed as such in #306.
> 
> I would suggest to alter it to use py2 on SLE12 codebase (py3 is not by default there) and py3 everywhere else.
> 
> Doing this runtime check is way too complex for no gain at all.

Done. I've pushed it so that it uses Python 2 for older than SLE 15.

**Comment by Conan-Kudo** [comment]
> > @DimStar77 I've proposed as such in #306.
> 
> I would suggest to alter it to use py2 on SLE12 codebase (py3 is not by default there) and py3 everywhere else.
> 
> Doing this runtime check is way too complex for no gain at all.

@fcrozat Done. I've pushed it so that it uses Python 2 for older than SLE 15.

**Pull request merged**
