### PR TITLE
Do not allow the abbreviation of cli arguments (bsc#1164543)

### PR DESCRIPTION
**Pull request by bzeller**

### CODE REVIEW

**Comment by DimStar77** [comment]
Will this mean the often used and documented "zypper in --no-r" won't work anymore?

**Comment by DimStar77** [comment]
at least transactional-updates (and thus possibly also other consumers) rely on --xml (short for --xmlout)

**Comment by bzeller** [comment]
> Will this mean the often used and documented "zypper in --no-r" won't work anymore?

Yes, all abbreviations will stop working, we decided to change that to not run into name clashes when introducing new switches. For example --reposd-dir did take arguments for --repo , which is problematic if we ever need a global --repo switch.

**Comment by bmwiedemann** [comment]
Will `zypper in --no-recommends` still work, or only `zypper install --no-recommends` ?

**Comment by bzeller** [comment]
> Will `zypper in --no-recommends` still work, or only `zypper install --no-recommends` ?

zypper in will still work. Thats only about the switches

**Pull request merged**
