### PR TITLE
Support listing gpgkey URLs in repo files (bsc#1088037)

### PR DESCRIPTION
**Pull request by bzeller**
Handles the new report introduced in libzypp for accepting package signing keys received via gpgkey urls in repo configuration files.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Wait, this didn't work before?

**Comment by bzeller** [comment]
No, those lines were ignored by libzypp and zypper before

**Comment by Conan-Kudo** [comment]
@bzeller You know that can be a newline or whitespace separate list, just like in `baseurl`, right?

**Comment by bzeller** [comment]
I did not touch the parser code for that. Libzypp always did parse and store it inside RepoInfo but never made use of the parsed information. If that parser is not handling all cases correctly that would be another feature/bug to look at.

**Pull request merged**
