### PR TITLE
subcommand: optimise fd-closing when running a subcommand

### PR DESCRIPTION
**Pull request by cyphar**
Iterating over (2,RLIMIT_NOFILE] and attempting to close(2) each fd is
quite expensive for two reasons:

1. It is very unlikely that the process already has RLIMIT_NOFILE file
   descriptors open, so many of the close(2) operations were unnecessary.

2. Because this is done *immediately* before an exec it's more expensive
   than setting O_CLOEXEC (which is handled in-kernel during execve(2)
   and is thus likely cheaper).

On most machines RLIMIT_NOFILE is 1024, so the cost of this is not
noticeable. However, inside containers RLIMIT_NOFILE can be in excess of
1 million -- which results in 1000x more close(2) operations. RPM had a
similar bug in the past, and was fixed [using the same /proc/self/fd
walking trick][1].

[1]: https://github.com/rpm-software-management/rpm/commit/5e6f05cd8dad

Reported-by: Marco Vedovati <mvedovati@suse.de>
Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by mlandres** [comment]
Thanks.

**Comment by cyphar** [comment]
Whoa whoa -- wait a second! I noticed a mistake and was about to fix it!

**Comment by cyphar** [comment]
Yes, it doesn't build. I already have fixed it though, I'll send a fixed patch in a second.

**Comment by cyphar** [comment]
#210 should fix it (it builds on my machine now).

**Pull request merged**
