### PR TITLE
New option --remove-orphaned to remove all orphaned packages in dup.

### PR DESCRIPTION
**Pull request by mlandres**
[bsc#1221525](https://bugzilla.suse.com/show_bug.cgi?id=1221525)

### CODE REVIEW

**Review by bzeller — APPROVED** [review]

**Comment by karlmistelberger** [comment]
Nice option. Many users ask for `--remove-unneeded`: https://forums.opensuse.org/search?q=zypper%20packages%20--unneeded%20order%3Alatest They currently use something like:
```
zypper packages --unneeded | grep "^i" | cut -d"|" -f3 | xargs zypper remove --clean-deps
```

**Comment by mlandres** [comment]
There will appear a `zypper remove --remove-unneeded` in #540

**Comment by ivan-mingolov-blue-technologies** [comment]
> There will appear a `zypper remove --remove-unneeded` in #540

Is that still the case, because I can't find such a change in #540 or you're planning to expose such an option in future PR?

**Comment by mlandres** [comment]
@ivan-mingolov-blue-technologies It will appear in a future PR. We got interrupted and releases what we dis so far.

**Pull request merged**
